# Generated by Django 3.0.3 on 2020-11-29 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('opening_hours', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=50)),
                ('machine_info', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('price_info', models.CharField(max_length=100)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Machine')),
            ],
        ),
    ]
