# Generated by Django 3.0.3 on 2020-11-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
