# Generated by Django 3.0.3 on 2020-11-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20201130_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
