# Generated by Django 3.0.3 on 2020-11-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20201130_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
